- app/src/main/kotlin/com/squareup/sort/main.kt
This produces this kind of values: `2022-11-25T20-07-30.843646500Z`
Fixes #10
> Replace illegal char on Windows

- app/src/main/kotlin/com/squareup/sort/SortCommand.kt
This allows errors during formatting passes to express that in exit codes
> Add PARSE_ERROR exit code if formatting fails

- app/src/main/kotlin/com/squareup/log/DelegatingLogger.kt
- app/src/main/kotlin/com/squareup/sort/SortCommand.kt
- app/src/main/kotlin/com/squareup/sort/main.kt
- app/src/test/groovy/com/squareup/SortCommandSpec.groovy
This adds a new `--quiet` argument to suppress noisy output unless there is an error. Logs are still recorded and written to the file, but only error outputs are printed and the log file location is printed if any errors were recorded.
Resolves #26
> Add --quiet argument

- .editorconfig
Taken from other Square projects.
Open to add other configs for `[*.{kt, kts}]` if needed.
> Add a basic `.editorconfig` file

- README.md
This helps users know the latest version more easily than going to the [tags page](https://github.com/square/gradle-dependencies-sorter/tags).
Beware, this solution uses the third party service [shields.io](https://shields.io/) to render the image.
> Add version badge to README.md

- .gitignore
Code is generated to `grammar/src/main/antlr/com/squareup/grammar/gen`, but the path glob didn't catch it.
local.properties should be ignored.
> Ignore local.properties and ANTLR codegen dir

- app/src/main/kotlin/com/squareup/sort/BuildDotGradleFinder.kt
- app/src/main/kotlin/com/squareup/sort/SortCommand.kt
Resolves #44. This simplifies it by skipping parallelism and using purely kotlin APIs. This also adds a new flag to control skipping hidden (i.e. dirs that start with `.`) and `build` dirs to improve speed.
> Fix path traversal issue + simplify

- app/src/main/kotlin/com/squareup/sort/SortCommand.kt
We run into the `FileAlreadyExistsException` during log file creation in about 1% of our CI builds with 16 workers. Though  rare it is a consistent occurrence over the past month and every time it happens we would need to rerun the task. Adding thread safety in the log file creation line so it'll try again without exiting if it happened to be that multiple threads try to create a file in the same place at the same time.
```
Exception in thread "main" java.nio.file.FileAlreadyExistsException: /tmp/dependencies-sorter/2023-04-05T21:51:56.445482Z.log
at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:94)
at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:1 …
```
> Add thread safety for log file creation

- README.md
All images are clickable by default but GitHub just opens the image. Instead, send people to the Maven Central page where they can get things historical version information.
> Have badge link to central

- grammar/src/main/antlr/com/squareup/grammar/GradleGroovyScript.g4
- grammar/src/test/groovy/com/squareup/grammar/GradleGroovyScriptSpec.groovy
- grammar/src/test/groovy/com/squareup/grammar/SimpleANTLRErrorListener.groovy
It is possible for build scripts to contain `project('...')` declarations in locations other than the `dependencies { /* ... */ }` and `buildscript { /* ... */ }` blocks.
For example, a plugin may support arbitrary configuration in top-level block like this:
```groovy
myVendorBlock {
applicableProjects = [ project(':foo:bar') ]
}
```
The Gradle Dependencies Sorter won't (and shouldn't!) know how to sort such things, since it won't have knowledge of vendor syntax. However, the sorter should just skip these blocks instead of complaining about syntax.
Resolves: https://github.com/square/gradle-dependencies-sorter/issues/36
> Tolerate project declarations in text blocks

- grammar/src/main/antlr/com/squareup/grammar/GradleGroovyScript.g4
- sort/src/test/groovy/com/squareup/sort/SorterSpec.groovy
Fixes first part of #57.
This change allows to call `add(configurationName: String, dependencyNotation: Any)` and similar functions.
I am aware this is not a common usecase. 
Please guide change for better solution.
> Sort add function call in depedencies

- README.md
- sort-dependencies-gradle-plugin/src/main/kotlin/com/squareup/sort/SortDependenciesPlugin.kt
- sort-dependencies-gradle-plugin/src/main/kotlin/com/squareup/sort/SortDependenciesTask.kt
- sort-dependencies-gradle-plugin/src/test/groovy/com/squareup/sort/FunctionalSpec.groovy
Resolves #60. This splits the gradle work into two tasks - one that runs the sorting and the other that checks it. This also wires the latter into the java-base `check` task.
CC @JakeWharton
> Split Gradle tasks into check and sort

- app/src/main/kotlin/com/squareup/sort/SortCommand.kt
- app/src/test/groovy/com/squareup/SortCommandSpec.groovy
- sort-dependencies-gradle-plugin/src/main/kotlin/com/squareup/sort/SortDependenciesTask.kt
- sort-dependencies-gradle-plugin/src/test/groovy/com/squareup/sort/FunctionalSpec.groovy
Resolves #61. This makes it run in "quiet" mode (i.e. errors only) by default, and you can make it louder with `--verbose`
> Flip quiet to verbose

- CHANGELOG.md
- grammar/src/main/antlr/com/squareup/grammar/GradleGroovyScript.g4
- grammar/src/test/groovy/com/squareup/grammar/SimpleANTLRErrorListener.groovy
```
./gradlew check
```
now succeeds locally.
> Move 'text' earlier in the grammar. For some reasons this fixes the tests.

- sort-dependencies-gradle-plugin/src/main/kotlin/com/squareup/sort/SortDependenciesExtension.kt
- sort-dependencies-gradle-plugin/src/main/kotlin/com/squareup/sort/SortDependenciesPlugin.kt
- sort-dependencies-gradle-plugin/src/test/groovy/com/squareup/sort/FunctionalSpec.groovy
Resolves https://github.com/square/gradle-dependencies-sorter/issues/22
Replaces https://github.com/square/gradle-dependencies-sorter/pull/25 (because it's easier to create a new PR then resolve diff conflict issues).
> Adds extension to permit setting custom program version.

- grammar/src/test/groovy/com/squareup/grammar/GradleGroovyScriptSpec.groovy
- sort/src/main/kotlin/com/squareup/sort/Sorter.kt
- sort/src/test/groovy/com/squareup/sort/SorterSpec.groovy
Resolves https://github.com/square/gradle-dependencies-sorter/issues/59
Note that it doesn't yet fix the issue with the location of the trailing `}`.
> Support multiple dependencies blocks (for e.g. KMP).

- gradle/libs.versions.toml
- sort/src/test/groovy/com/squareup/sort/SorterSpec.groovy
- `gradle-script-grammar:v0.3` adds an enhancement that supports sorting dependencies with multiple closures
- See https://github.com/autonomousapps/gradle-script-grammar/pull/1
- This PR updates grammar library to `v0.3`
- Land _after_ new version is released
> Update to use gradle-script-grammar v0.3

- sort-dependencies-gradle-plugin/src/main/kotlin/com/squareup/sort/SortDependenciesTask.kt
This treated it like an assignable argument when it's actually a flag, so the task always ran verbosely
> Fix verbose flag in SortDependenciesTask

- app/build.gradle
- app/src/main/kotlin/com/squareup/sort/BuildDotGradleFinder.kt
- app/src/main/kotlin/com/squareup/sort/SortCommand.kt
- app/src/main/kotlin/com/squareup/sort/main.kt
- app/src/test/groovy/com/squareup/SortCommandSpec.groovy
- app/src/test/groovy/com/squareup/sort/BuildDotGradleFinderTest.groovy
- gradle/libs.versions.toml
Funny enough, its better strictness would've also caught #90 😅
> Switch to Clikt

- .github/workflows/pr.yml
- .github/workflows/publish.yml
- CHANGELOG.md
- build-logic/src/main/kotlin/com/squareup/convention/publishing/Publishing.kt
- build-logic/src/main/kotlin/nexus/Credentials.kt
- gradle.properties
- gradle/libs.versions.toml
- gradle/wrapper/gradle-wrapper.properties
With inspiration from https://github.com/square/okhttp/blob/master/.github/workflows/build.yml#L17-L44.
Square now requires releases to be published from Github Actions. I think/hope this is configured correctly.
> Prepare for release 0.7.

- app/src/main/kotlin/com/squareup/sort/SortCommand.kt
- sort-dependencies-gradle-plugin/src/main/kotlin/com/squareup/sort/SortDependenciesPlugin.kt
- sort-dependencies-gradle-plugin/src/main/kotlin/com/squareup/sort/SortDependenciesTask.kt
- sort-dependencies-gradle-plugin/src/test/groovy/com/squareup/sort/FunctionalSpec.groovy
Gradle or CLI.
Resolves https://github.com/square/gradle-dependencies-sorter/issues/89.
> fix: suggest fix action based on invocation context.

- sort/src/main/kotlin/com/squareup/sort/Configuration.kt
- sort/src/test/groovy/com/squareup/sort/ConfigurationSpec.groovy
- sort/src/test/groovy/com/squareup/sort/GroovySorterSpec.groovy
- sort/src/test/groovy/com/squareup/sort/KotlinSorterSpec.groovy
Validates that https://github.com/square/gradle-dependencies-sorter/issues/113 is a non-issue, but also adjusts the sort order a bit.
> fix: verify supporrt for stringified configurations. Adjust sort order.

- app/src/main/kotlin/com/squareup/sort/SortCommand.kt
It was supposed to do this, but we stopped calling logger.error(), which is what would trigger that behavior.
Resolves https://github.com/square/gradle-dependencies-sorter/issues/122
As a follow-up, consider adding a verbose property to the extension.
> fix: emit errors even when not in verbose mode.

- app/src/main/kotlin/com/squareup/sort/SortCommand.kt
- sort-dependencies-gradle-plugin/src/main/kotlin/com/squareup/sort/SortDependenciesExtension.kt
- sort-dependencies-gradle-plugin/src/main/kotlin/com/squareup/sort/SortDependenciesPlugin.kt
- sort-dependencies-gradle-plugin/src/main/kotlin/com/squareup/sort/SortDependenciesTask.kt
- sort-dependencies-gradle-plugin/src/test/groovy/com/squareup/sort/FunctionalSpec.groovy
- sort/src/main/kotlin/com/squareup/sort/Sorter.kt
- sort/src/main/kotlin/com/squareup/sort/groovy/GroovySorter.kt
- sort/src/main/kotlin/com/squareup/sort/kotlin/KotlinSorter.kt
- sort/src/test/groovy/com/squareup/sort/GroovySorterSpec.groovy
- sort/src/test/groovy/com/squareup/sort/KotlinSorterSpec.groovy
Basically, this adds a flag to the CLI tool and the Gradle plugin to disable auto-insertion of blank lines between blocks of different configurations. So currently it will generate something like:
```kotlin
dependencies {
api(libs.a)
api(libs.b)
implementation(libs.c)
testImplementation(libs.d)
testImplementation(libs.e)
}
```
When this flag is set to false, you get:
```kotlin
dependencies {
api(libs.a)
api(libs.b)
implementation(libs.c)
testImplementation(libs.d)
testImplementation(libs.e)
}
```
as in the test cases. Yes I realise this is petty - I just prefer it without blank lines :slightly_smiling_face:
I'm not 100% sure on the double-negativity of the CLI flag - any feedback/suggestions on that is welcome.
> Add flag to disable blank lines between configurations

- build-logic/src/main/kotlin/com/squareup/convention/AppConvention.kt
- gradle/libs.versions.toml
- sort/src/test/groovy/com/squareup/sort/DependencyComparatorTest.groovy
Resolves https://github.com/square/gradle-dependencies-sorter/issues/128 (I think)
> chore: remove unused entries from version catalog.
